name: Deploy-frontend-to-stage
on: 
  push:
    branches:
      -main
    paths:
      - 'package.json'
jobs:
  deploy-to-stage: 
    runs-on: ubuntu-latest
    steps: 
      - name: check for version change
        id:  version_changed
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true # Search for changes in the commit

      - name: hello-world
        run: exho "Hello world"
        
